expose_php = Off
display_errors = Off
log_errors = On
error_log = /var/log/nexor/php-errors.log
upload_max_filesize = 32M
post_max_size = 40M
memory_limit = 256M
max_execution_time = 120
session.cookie_httponly = 1
session.cookie_secure = 1

